apiVersion: v1
kind: ConfigMap
metadata:
  name: chart-museum-manager-config
  labels:
    app: chart-museum-manager
data:
  # 可在此添加前端运行时配置
  # 例如 API 地址等（如需注入到容器中）
  VITE_CHARTMUSEUM_API: "http://10.1.0.7:30091"
