apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: chartmuseum-manager
  labels:
    app: chartmuseum-manager
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
spec:
  ingressClassName: nginx
  rules:
    - host: chartmuseum-manager.example.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: chartmuseum-manager
                port:
                  name: http
