apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - configmap.yaml
  - deployment.yaml
  - service.yaml
  - ingress.yaml
  - middleware.yaml

labels:
  - pairs:
      app: chart-museum-manager
      version: v1.0.0

# 可在此设置命名空间
namespace: production

# 可在此设置镜像
images:
  # 通过 Kustomize 统一管理镜像地址和标签，避免在 deployment.yaml 中硬编码 registry 与 tag
  - name: chart-museum-manager
    newName: ccr.ccs.tencentyun.com/cmrhyq/dev
    newTag: chartMuseumManager-v1.0.0
